services:
    pv.hh:
        class: Pv\MyBundle\Helper\HH
        arguments:
            - @service_container
    pv.cc:
        class: Pv\MyBundle\Helper\CC
        arguments:
            - @service_container

    pv.html_helper:
        class: Pv\MyBundle\Templating\HtmlHelper
        arguments:
            - @service_container
    pv.twig_extension:
        class: Pv\MyBundle\Templating\TwigExtension
        arguments:
            - @pv.html_helper
        tags:
            - { name: twig.extension }

    pv.pagelet_manager:
        class: Pv\MyBundle\PageletLib\PageletManager
        arguments:
            - @service_container
